name: Test Build
run-name: self-hosted

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  build:
    name: Test Build
    runs-on: self-hosted #ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm i

      - name: Build Astro Website
        run: pnpm build
