name: Test Build
permissions:
  contents: read

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm i

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_NASA_API: DEMO_KEY
          envkey_AZURE_API: DEMO_KEY
        
      - name: Build Astro Website
        run: pnpm build
